import { useCallback, useEffect, useRef, useState } from 'react'
import type { PropsLocale, PropsRuntime } from '@deepseek-ai/dsh-client-ui-slots'
import type { SponsorDemoAdFailureReason } from '@deepseek-ai/dsh-sponsor-demo/types'
import type {
  SponsoredRunChatData,
  SponsorDemoAdVerificationData,
  SponsorDemoReceiptData,
  SponsorDemoRewardQuoteData,
  SponsorDemoTokenGrantRevocationData,
  SponsorDemoTokenGrantSettlementData,
} from './sponsor-definition.ts'
import { deriveSponsorReceiptUsage, type SponsorReceiptUsage } from './receipt-usage.ts'
import { LOCAL_SPONSOR_VIDEO_ASSET_ID, LOCAL_SPONSOR_VIDEO_SOURCES } from './test-video.ts'
import {
  TENCENT_GDT_NATIVE_MOCK_ASSET_ID,
  TENCENT_GDT_NATIVE_MOCK_PLACEMENT_ID,
  TENCENT_PC_LOCAL_MOCK,
  type TencentPcNativeTemplateCreative,
} from './tencent-pc-mock.ts'
import css from './ReasoningSponsor.module.css'

/** Typed Host actions admitted for the legacy in-Think rewarded playback. */
export type SponsorPlaybackAction = 'start' | 'complete'

/** Typed Host actions admitted for the Tencent-compatible sandbox lifecycle. */
export type SponsorAdAction = 'load' | 'render' | 'impression'

/** Settled browser-facing result for one sandbox lifecycle transition. */
export interface SponsorAdActionResult {
  /** Present only when the transport or Host state machine refused the transition. */
  readonly error: string | null
  /** Host-issued request identity returned by `load`; never generated by the browser. */
  readonly opaqueId?: string
}

/** Addressed Remote face injected into the reasoning sponsor occupant. */
export interface ReasoningSponsorInjected {
  /** Record explicit one-time consent before any ad lifecycle transition. */
  readonly acceptSponsorship: (runId: string) => Promise<string | null>
  /** Admit one legacy playback transition for the exact durable run. */
  readonly updatePlayback: (
    runId: string,
    action: SponsorPlaybackAction,
  ) => Promise<string | null>
  /** Admit one Tencent sandbox transition; only `load` may omit `requestId`. */
  readonly updateAd: (
    runId: string,
    action: SponsorAdAction,
    requestId?: string,
  ) => Promise<SponsorAdActionResult>
  /** Revoke the unused provisional allowance after a local ad failure. */
  readonly failAd: (runId: string, reason: SponsorDemoAdFailureReason) => Promise<string | null>
}

/** Props for the single session-scoped reasoning sponsorship occupant. */
export type ReasoningSponsorProps = PropsRuntime<'conversation.chat.reasoning.sponsor'>
  & PropsLocale<'sponsorDemo'>
  & ReasoningSponsorInjected

type LocalError = 'accept' | 'asset' | 'load' | 'render' | 'impression' | 'playback' | 'start' | 'complete'
type PendingAction = 'accept' | SponsorPlaybackAction | SponsorAdAction
type LocalAdKind = 'video' | 'tencent-native-template' | 'unknown'

const COUNT_FORMAT = new Intl.NumberFormat('zh-CN')
const CURRENCY_FORMAT = new Intl.NumberFormat('zh-CN', {
  style: 'currency', currency: 'CNY', minimumFractionDigits: 2, maximumFractionDigits: 4,
})

function formatCount(value: number): string { return COUNT_FORMAT.format(value) }
function formatSeconds(valueMs: number): string { return String(Math.max(0, Math.round(valueMs / 1_000))) }
function formatMicros(value: number): string { return CURRENCY_FORMAT.format(value / 1_000_000) }

function clock(valueMs: number): string {
  const seconds = Math.max(0, Math.ceil(valueMs / 1_000))
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`
}

function resolveLocalAdKind(data: SponsoredRunChatData): LocalAdKind {
  if (
    data.assetId === LOCAL_SPONSOR_VIDEO_ASSET_ID
    && data.adProvider === 'local-video'
    && data.adFormat === 'rewarded-video'
  ) return 'video'
  const loadedMatches = data.adLoaded === undefined || (
    data.adLoaded.placementId === TENCENT_GDT_NATIVE_MOCK_PLACEMENT_ID
    && data.adLoaded.creativeId === TENCENT_GDT_NATIVE_MOCK_ASSET_ID
  )
  if (
    data.assetId === TENCENT_GDT_NATIVE_MOCK_ASSET_ID
    && data.adProvider === 'tencent-gdt-sandbox'
    && data.adFormat === 'native-template'
    && loadedMatches
  ) return 'tencent-native-template'
  return 'unknown'
}

function GrantLifecycle({ data, t }: {
  readonly data: SponsoredRunChatData
  readonly t: ReasoningSponsorProps['t']
}) {
  if (data.tokenGrant === undefined && data.tokenGrantSettlement === undefined) return null
  const verified = data.adVerification?.signatureVerified === true
    || data.tokenGrantSettlement !== undefined
  const settled = data.tokenGrantSettlement !== undefined
  const stages = [
    { label: t('reasoning.lifecycle.issued'), done: true },
    { label: t('reasoning.lifecycle.verified'), done: verified },
    { label: t('reasoning.lifecycle.settled'), done: settled },
  ]
  return (
    <ol className={css.grantLifecycle} aria-label={t('reasoning.lifecycle.aria')}>
      {stages.map((stage, index) => (
        <li key={stage.label} data-complete={stage.done ? 'true' : 'false'}>
          <span aria-hidden="true">{stage.done ? '✓' : index + 1}</span>
          {stage.label}
        </li>
      ))}
    </ol>
  )
}

function QuoteSummary({ data, t, compact = false }: {
  readonly data: Pick<SponsoredRunChatData, 'operatorInputSubsidyMicros' | 'rewardQuote'>
  readonly t: ReasoningSponsorProps['t']
  readonly compact?: boolean | undefined
}) {
  const quote: SponsorDemoRewardQuoteData | undefined = data.rewardQuote
  if (quote === undefined) return null
  return (
    <div
      className={css.quoteSummary}
      data-compact={compact ? 'true' : 'false'}
      data-sponsor-quote-id={quote.quoteId}
    >
      <span className={css.quoteLabel}>{t('reasoning.quote.label')}</span>
      <strong>{t('reasoning.quote.value', { amount: formatMicros(quote.simulatedAdValueMicros) })}</strong>
      <span>{t('reasoning.quote.ecpm', { amount: formatMicros(quote.marketBenchmarkEcpmMicros) })}</span>
      <span data-sponsor-ad-contribution-micros={quote.fundedBudgetMicros}>
        {t('reasoning.quote.adContribution', { amount: formatMicros(quote.fundedBudgetMicros) })}
      </span>
      {data.operatorInputSubsidyMicros === undefined ? null : (
        <span data-sponsor-operator-input-subsidy-micros={data.operatorInputSubsidyMicros}>
          {t('reasoning.quote.operatorInputSubsidy', {
            amount: formatMicros(data.operatorInputSubsidyMicros),
          })}
        </span>
      )}
      <span className={css.quoteReward}>{t('reasoning.quote.reward', {
        count: formatCount(quote.rewardTokens),
      })}</span>
      <small>{t('reasoning.quote.disclosure')}</small>
    </div>
  )
}

function CompactReceipt({ receipt, usage, verification, settlement, revocation, t }: {
  readonly receipt: SponsorDemoReceiptData
  readonly usage: SponsorReceiptUsage
  readonly verification?: SponsorDemoAdVerificationData | undefined
  readonly settlement?: SponsorDemoTokenGrantSettlementData | undefined
  readonly revocation?: SponsorDemoTokenGrantRevocationData | undefined
  readonly t: ReasoningSponsorProps['t']
}) {
  return (
    <details className={css.receiptDetails} data-sponsor-receipt>
      <summary>{t('reasoning.receipt.toggle')}</summary>
      <dl>
        <div><dt>{t('reasoning.receipt.route')}</dt><dd>{receipt.model} / {receipt.provider}</dd></div>
        <div>
          <dt>{t('reasoning.receipt.fundingMode')}</dt>
          <dd>{receipt.fundingMode === 'current-credential-simulation'
            ? t('reasoning.funding.simulation')
            : t('reasoning.funding.dedicated')}</dd>
        </div>
        <div>
          <dt>{t('reasoning.receipt.usage')}</dt>
          <dd>{t('reasoning.receipt.usage.value', {
            input: formatCount(usage.inputTokens), output: formatCount(usage.outputTokens),
          })}</dd>
        </div>
        {usage.effectiveBudgetMicros === undefined ? null : (
          <div data-sponsor-effective-budget-micros={usage.effectiveBudgetMicros}>
            <dt>{t('reasoning.receipt.reservedBudget')}</dt>
            <dd>{formatMicros(usage.effectiveBudgetMicros)}</dd>
          </div>
        )}
        {usage.effectiveBudgetMicros !== undefined || usage.quotedBudgetMicros === undefined ? null : (
          <div data-sponsor-quoted-budget-micros={usage.quotedBudgetMicros}>
            <dt>{t('reasoning.receipt.quotedBudget')}</dt>
            <dd>{formatMicros(usage.quotedBudgetMicros)}</dd>
          </div>
        )}
        {usage.simulatedAdContributionMicros === undefined ? null : (
          <div data-sponsor-ad-contribution-micros={usage.simulatedAdContributionMicros}>
            <dt>{t('reasoning.receipt.adContribution')}</dt>
            <dd>{formatMicros(usage.simulatedAdContributionMicros)}</dd>
          </div>
        )}
        {usage.operatorInputSubsidyMicros === undefined ? null : (
          <div data-sponsor-operator-input-subsidy-micros={usage.operatorInputSubsidyMicros}>
            <dt>{t('reasoning.receipt.operatorInputSubsidy')}</dt>
            <dd>{formatMicros(usage.operatorInputSubsidyMicros)}</dd>
          </div>
        )}
        <div>
          <dt>{t('reasoning.receipt.simulatedCost')}</dt>
          <dd>{receipt.costKind === 'configured-estimate'
            ? t('reasoning.receipt.simulatedCost.value', { amount: formatMicros(usage.estimatedCostMicros) })
            : t('reasoning.receipt.unavailable')}</dd>
        </div>
        <div>
          <dt>{t('reasoning.receipt.externalCost')}</dt>
          <dd>{receipt.actualCostMicros === null
            ? t('reasoning.receipt.unavailable')
            : formatMicros(receipt.actualCostMicros)}</dd>
        </div>
        {receipt.adLedger === undefined ? null : (
          <div>
            <dt>{t('reasoning.receipt.adSettlement')}</dt>
            <dd>{t('reasoning.receipt.adSettlement.value', {
              amount: formatMicros(receipt.adLedger.externalRevenueMicros),
            })}</dd>
          </div>
        )}
        {receipt.rewardQuote === undefined ? null : (
          <div>
            <dt>{t('reasoning.receipt.quote')}</dt>
            <dd>{t('reasoning.receipt.quote.value', {
              amount: formatMicros(receipt.rewardQuote.simulatedAdValueMicros),
              count: formatCount(receipt.rewardQuote.rewardTokens),
            })}</dd>
          </div>
        )}
        {verification === undefined ? null : (
          <div>
            <dt>{t('reasoning.receipt.tencentVerification')}</dt>
            <dd>{t('reasoning.receipt.tencentVerification.value')}</dd>
          </div>
        )}
        {settlement === undefined ? null : (
          <div>
            <dt>{t('reasoning.receipt.tokenSettlement')}</dt>
            <dd>{t('reasoning.receipt.tokenSettlement.redeemed', {
              count: formatCount(settlement.redeemedTokens),
            })}</dd>
          </div>
        )}
        {revocation === undefined ? null : (
          <div>
            <dt>{t('reasoning.receipt.tokenSettlement')}</dt>
            <dd>{t('reasoning.receipt.tokenSettlement.revoked', {
              count: formatCount(revocation.revokedTokens),
            })}</dd>
          </div>
        )}
        {usage.latestConsumption === undefined ? null : (
          <>
            <div>
              <dt>{t('reasoning.receipt.sponsorCall')}</dt>
              <dd>{usage.latestConsumption.model} / {usage.latestConsumption.provider}</dd>
            </div>
            <div>
              <dt>{t('reasoning.receipt.sponsorUsage')}</dt>
              <dd>{t('reasoning.receipt.usage.value', {
                input: formatCount(usage.inputTokens), output: formatCount(usage.outputTokens),
              })}</dd>
            </div>
            <div>
              <dt>{t('reasoning.receipt.remaining')}</dt>
              <dd>{t('reasoning.receipt.remaining.value', {
                tokens: formatCount(usage.latestConsumption.remainingTokens),
                steps: formatCount(usage.latestConsumption.remainingSteps),
              })}</dd>
            </div>
          </>
        )}
      </dl>
    </details>
  )
}

/** Render a fixed local test ad without exposing ad copy to reasoning or model payloads. */
export function ReasoningSponsor({
  turn, step, assistantStatus, onPlaybackStateChange, useSession,
  acceptSponsorship, updatePlayback, updateAd, failAd, t,
}: ReasoningSponsorProps) {
  const data = useSession(snapshot => snapshot.chat.timeline.turns.get(turn)
    ?.steps.find(candidate => candidate.step === step)?.data.get('sponsored-run'))
  const [startingAdmitted, setStartingAdmitted] = useState(false)
  const [locallyAccepted, setLocallyAccepted] = useState(false)
  const [playing, setPlaying] = useState(false)
  const [locallyEnded, setLocallyEnded] = useState(false)
  const [elapsedMs, setElapsedMs] = useState(0)
  const [attempt, setAttempt] = useState(0)
  const [nativeCreative, setNativeCreative] = useState<TencentPcNativeTemplateCreative | null>(null)
  const [nativeRequestId, setNativeRequestId] = useState<string | null>(null)
  const [nativeRenderedRequestId, setNativeRenderedRequestId] = useState<string | null>(null)
  const [pending, setPending] = useState<PendingAction | null>(null)
  const [error, setError] = useState<LocalError | null>(null)
  const inFlightRef = useRef<PendingAction | null>(null)
  const startFlowRef = useRef(false)
  const endedRef = useRef(false)
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const renderRequestedRef = useRef<string | null>(null)
  const impressionRequestedRef = useRef<string | null>(null)
  const failedRunRef = useRef<string | null>(null)
  const mountedRef = useRef(true)

  const localAdKind = data === undefined ? 'unknown' : resolveLocalAdKind(data)
  const legacyReward = data?.reward ?? (data?.receipt?.rewardIssued === true
    ? { watchedMs: data.receipt.watchedMs, grantedTokens: data.receipt.grantedTokens }
    : undefined)
  const reward = localAdKind === 'tencent-native-template' && data?.tokenGrantSettlement !== undefined
    ? { watchedMs: data.adDurationMs, grantedTokens: data.tokenGrantSettlement.redeemedTokens }
    : legacyReward
  const quotedRewardTokens = data?.rewardQuote?.rewardTokens ?? data?.rewardTokens ?? 0
  const sponsorshipUsed = (data?.tokenConsumptions?.length ?? 0) > 0
    || data?.receipt?.sponsorshipUsed === true
  const knownAsset = localAdKind !== 'unknown' && (localAdKind !== 'video'
    || data?.playback === undefined || data.playback.assetId === data.assetId)
  const accepted = locallyAccepted || data?.decision === 'accepted'
  const admitted = startingAdmitted || data?.playback !== undefined
  const effectiveNativeRequestId = data?.adLoaded?.requestId ?? nativeRequestId
  const nativeRendered = effectiveNativeRequestId !== null && (
    data?.adRendered?.requestId === effectiveNativeRequestId
    || nativeRenderedRequestId === effectiveNativeRequestId
  )
  const nativeTotalMs = data?.adDurationMs ?? 0
  const fundingLabel = data?.fundingMode === 'current-credential-simulation'
    ? t('reasoning.funding.simulation')
    : t('reasoning.funding.dedicated')
  const rewardStatus = data?.tokenGrantSettlement !== undefined
    ? t('reasoning.grant.redeemed')
    : sponsorshipUsed
      ? t('reasoning.route.used')
      : data?.tokenGrant !== undefined || data?.receipt?.rewardIssued === true
        ? t('reasoning.grant.issued')
        : localAdKind === 'tencent-native-template'
          ? t('reasoning.tencent.settlement')
          : t('reasoning.simulated')

  const reportAdFailure = useCallback((reason: SponsorDemoAdFailureReason): void => {
    if (data === undefined || failedRunRef.current === data.runId) return
    failedRunRef.current = data.runId
    void failAd(data.runId, reason).then((failure) => {
      if (failure !== null && failedRunRef.current === data.runId) failedRunRef.current = null
    }).catch(() => {
      if (failedRunRef.current === data.runId) failedRunRef.current = null
    })
  }, [data, failAd])

  useEffect(() => () => { mountedRef.current = false }, [])

  useEffect(() => {
    if (
      data?.playback === undefined || reward !== undefined || locallyEnded || !knownAsset
    ) return
    setPlaying(true)
  }, [data?.playback, knownAsset, locallyEnded, reward])

  useEffect(() => {
    if (
      localAdKind !== 'tencent-native-template' || reward !== undefined
    ) return
    if (data?.adLoaded !== undefined) {
      setNativeRequestId(data.adLoaded.requestId)
      if (data.adImpression === undefined && error === null) setPlaying(true)
    }
    if (data?.adRendered !== undefined) setNativeRenderedRequestId(data.adRendered.requestId)
    if (data?.adImpression !== undefined) {
      setLocallyEnded(true)
      setPlaying(false)
    }
  }, [data?.adImpression, data?.adLoaded, data?.adRendered, error, localAdKind, reward])

  useEffect(() => {
    onPlaybackStateChange(false)
    return () => { onPlaybackStateChange(false) }
  }, [onPlaybackStateChange])

  const runAccept = useCallback(async (): Promise<boolean> => {
    if (data === undefined || inFlightRef.current !== null) return false
    inFlightRef.current = 'accept'
    setPending('accept')
    setError(null)
    try {
      const failure = await acceptSponsorship(data.runId)
      if (!mountedRef.current) return false
      if (failure !== null) { setError('accept'); return false }
      setLocallyAccepted(true)
      return true
    } catch {
      if (mountedRef.current) setError('accept')
      return false
    } finally {
      inFlightRef.current = null
      if (mountedRef.current) setPending(null)
    }
  }, [acceptSponsorship, data])

  const runPlaybackAction = useCallback(async (action: SponsorPlaybackAction): Promise<boolean> => {
    if (data === undefined || inFlightRef.current !== null) return false
    inFlightRef.current = action
    setPending(action)
    setError(null)
    try {
      const failure = await updatePlayback(data.runId, action)
      if (!mountedRef.current) return false
      if (failure !== null) { setError(action); return false }
      return true
    } catch {
      if (mountedRef.current) setError(action)
      return false
    } finally {
      inFlightRef.current = null
      if (mountedRef.current) setPending(null)
    }
  }, [data, updatePlayback])

  const runAdAction = useCallback(async (
    action: SponsorAdAction, requestId?: string,
  ): Promise<SponsorAdActionResult | null> => {
    if (data === undefined || inFlightRef.current !== null) return null
    inFlightRef.current = action
    setPending(action)
    setError(null)
    try {
      return await updateAd(data.runId, action, requestId)
    } catch {
      return { error: 'sponsor ad transport failed' }
    } finally {
      inFlightRef.current = null
      if (mountedRef.current) setPending(null)
    }
  }, [data, updateAd])

  useEffect(() => {
    const video = videoRef.current
    if (!playing || localAdKind !== 'video' || video === null) return
    try {
      void video.play().catch(() => {
        reportAdFailure('playback-incomplete')
        setPlaying(false)
        setError('playback')
      })
    } catch {
      reportAdFailure('playback-incomplete')
      setPlaying(false)
      setError('playback')
    }
  }, [attempt, localAdKind, playing, reportAdFailure])

  const startNative = useCallback(async (): Promise<void> => {
    if (data === undefined || inFlightRef.current !== null) return
    if (!knownAsset || localAdKind !== 'tencent-native-template') { setError('asset'); return }
    let requestId = effectiveNativeRequestId
    if (requestId === null) {
      const result = await runAdAction('load')
      if (result === null || !mountedRef.current) return
      if (result.error !== null || result.opaqueId === undefined) {
        reportAdFailure('load-failed')
        setError('load')
        return
      }
      requestId = result.opaqueId
      setNativeRequestId(requestId)
    }
    renderRequestedRef.current = null
    impressionRequestedRef.current = null
    endedRef.current = false
    setLocallyEnded(false)
    setElapsedMs(0)
    setNativeCreative(null)
    setNativeRenderedRequestId(null)
    setError(null)
    setAttempt(value => value + 1)
    setPlaying(true)
  }, [data, effectiveNativeRequestId, knownAsset, localAdKind, reportAdFailure, runAdAction])

  const startVideo = useCallback(async (): Promise<void> => {
    if (data === undefined || inFlightRef.current !== null) return
    if (!knownAsset || localAdKind !== 'video') { setError('asset'); return }
    if (!admitted) {
      const accepted = await runPlaybackAction('start')
      if (!mountedRef.current) return
      if (!accepted) {
        reportAdFailure('playback-incomplete')
        return
      }
      setStartingAdmitted(true)
    }
    endedRef.current = false
    setLocallyEnded(false)
    setElapsedMs(0)
    setError(null)
    setAttempt(value => value + 1)
    setPlaying(true)
  }, [admitted, data, knownAsset, localAdKind, reportAdFailure, runPlaybackAction])

  const resumeAcceptedAd = useCallback(async (): Promise<void> => {
    if (
      data === undefined || data.decision !== 'accepted' || data.tokenGrant === undefined
      || data.tokenGrantSettlement !== undefined
      || data.tokenGrantRevocation !== undefined || data.adImpression !== undefined
      || reward !== undefined || locallyEnded || error !== null || startFlowRef.current
    ) return
    if (!knownAsset) {
      setError('asset')
      reportAdFailure(data.adFormat === 'rewarded-video' ? 'playback-incomplete' : 'load-failed')
      return
    }
    const shouldLoadNative = localAdKind === 'tencent-native-template'
      && effectiveNativeRequestId === null
    const shouldStartVideo = localAdKind === 'video' && !admitted
    if (!shouldLoadNative && !shouldStartVideo) return
    startFlowRef.current = true
    try {
      if (shouldLoadNative) await startNative()
      else await startVideo()
    } finally {
      startFlowRef.current = false
    }
  }, [
    admitted, data, effectiveNativeRequestId, error, knownAsset, localAdKind, locallyEnded,
    reportAdFailure, reward, startNative, startVideo,
  ])

  useEffect(() => { void resumeAcceptedAd() }, [resumeAcceptedAd])

  const start = useCallback(async (): Promise<void> => {
    if (
      data === undefined || assistantStatus !== 'running' || data.receipt !== undefined
      || (data.decision !== undefined && data.decision !== 'accepted') || startFlowRef.current
    ) return
    if (!knownAsset) { setError('asset'); return }
    startFlowRef.current = true
    try {
      if (!accepted && !await runAccept()) return
      if (!mountedRef.current) return
      if (localAdKind === 'tencent-native-template') await startNative()
      else await startVideo()
    } finally {
      startFlowRef.current = false
    }
  }, [accepted, assistantStatus, data, knownAsset, localAdKind, runAccept, startNative, startVideo])

  const completeVideo = useCallback(async (): Promise<void> => {
    if (endedRef.current || data === undefined || reward !== undefined) return
    endedRef.current = true
    setLocallyEnded(true)
    setPlaying(false)
    const accepted = await runPlaybackAction('complete')
    if (!accepted) {
      endedRef.current = false
      reportAdFailure('verification-rejected')
    }
  }, [data, reportAdFailure, reward, runPlaybackAction])

  const recordNativeImpression = useCallback(async (): Promise<void> => {
    const requestId = effectiveNativeRequestId
    if (requestId === null || reward !== undefined || impressionRequestedRef.current === requestId) return
    impressionRequestedRef.current = requestId
    setLocallyEnded(true)
    setPlaying(false)
    const result = await runAdAction('impression', requestId)
    if (result === null || result.error === null) return
    impressionRequestedRef.current = null
    endedRef.current = false
    reportAdFailure('verification-rejected')
    if (mountedRef.current) setError('impression')
  }, [effectiveNativeRequestId, reportAdFailure, reward, runAdAction])

  useEffect(() => {
    if (
      localAdKind !== 'tencent-native-template' || !playing || reward !== undefined
      || effectiveNativeRequestId === null
    ) return
    let current = true
    setNativeCreative(null)
    void TENCENT_PC_LOCAL_MOCK.loadNativeAdData({
      placementId: TENCENT_GDT_NATIVE_MOCK_PLACEMENT_ID, count: 1,
    }).then(([creative]) => {
      if (!current) return
      const expectedCreativeId = data?.adLoaded?.creativeId ?? TENCENT_GDT_NATIVE_MOCK_ASSET_ID
      if (
        creative === undefined
        || creative.placementId !== TENCENT_GDT_NATIVE_MOCK_PLACEMENT_ID
        || creative.advertisementId !== expectedCreativeId
      ) {
        reportAdFailure('load-failed')
        setPlaying(false)
        setError('load')
        return
      }
      setNativeCreative(creative)
    }).catch(() => {
      if (!current) return
      reportAdFailure('load-failed')
      setPlaying(false)
      setError('load')
    })
    return () => { current = false }
  }, [attempt, data?.adLoaded?.creativeId, effectiveNativeRequestId, localAdKind, playing, reportAdFailure, reward])

  useEffect(() => {
    const requestId = effectiveNativeRequestId
    if (
      localAdKind !== 'tencent-native-template' || !playing || nativeCreative === null
      || requestId === null || nativeRendered || renderRequestedRef.current === requestId
    ) return
    renderRequestedRef.current = requestId
    void runAdAction('render', requestId).then((result) => {
      if (result === null || !mountedRef.current) return
      if (result.error !== null) {
        renderRequestedRef.current = null
        reportAdFailure('render-failed')
        setPlaying(false)
        setError('render')
        return
      }
      setNativeRenderedRequestId(requestId)
    })
  }, [effectiveNativeRequestId, localAdKind, nativeCreative, nativeRendered, playing, reportAdFailure, runAdAction])

  useEffect(() => {
    if (
      localAdKind !== 'tencent-native-template' || !playing || nativeCreative === null
      || !nativeRendered || nativeTotalMs <= 0
    ) return
    let accumulatedVisibleMs = 0
    let visibleSince = document.visibilityState === 'visible' ? Date.now() : null
    let stopped = false
    const measuredVisibleMs = (): number => visibleSince === null
      ? accumulatedVisibleMs
      : accumulatedVisibleMs + Math.max(0, Date.now() - visibleSince)
    const update = (): void => {
      if (stopped) return
      const next = Math.min(nativeTotalMs, measuredVisibleMs())
      setElapsedMs(next)
      if (next >= nativeTotalMs) { stopped = true; void recordNativeImpression() }
    }
    const visibilityChanged = (): void => {
      if (document.visibilityState === 'visible') {
        if (visibleSince === null) visibleSince = Date.now()
      } else if (visibleSince !== null) {
        accumulatedVisibleMs += Math.max(0, Date.now() - visibleSince)
        visibleSince = null
      }
      update()
    }
    update()
    const timer = window.setInterval(update, 100)
    document.addEventListener('visibilitychange', visibilityChanged)
    return () => {
      stopped = true
      window.clearInterval(timer)
      document.removeEventListener('visibilitychange', visibilityChanged)
    }
  }, [localAdKind, nativeCreative, nativeRendered, nativeTotalMs, playing, recordNativeImpression])

  if (data?.presentation !== 'reasoning-card') return null

  if (data.tokenGrantRevocation !== undefined && data.tokenGrantSettlement === undefined) {
    return (
      <aside className={`${css.rail} ${css.errorRail}`} aria-label={t('reasoning.aria')} data-reasoning-sponsor="revoked">
        <span className={css.testBadge}>{t('reasoning.badge')}</span>
        <span role="status">{t('reasoning.grant.revoked')}</span>
        <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
          {fundingLabel}
        </span>
        <QuoteSummary data={data} t={t} compact />
        <GrantLifecycle data={data} t={t} />
        {data.receipt === undefined ? null : (
          <CompactReceipt
            receipt={data.receipt}
            usage={deriveSponsorReceiptUsage(data.receipt, data.tokenConsumptions, {
              tokenGrant: data.tokenGrant,
              operatorInputSubsidyMicros: data.operatorInputSubsidyMicros,
            })}
            verification={data.adVerification}
            settlement={data.tokenGrantSettlement}
            revocation={data.tokenGrantRevocation}
            t={t}
          />
        )}
      </aside>
    )
  }

  if (reward !== undefined) {
    return (
      <aside className={`${css.rail} ${css.rewardRail}`} aria-label={t('reasoning.aria')} data-reasoning-sponsor="rewarded">
        <span className={css.testBadge}>{t('reasoning.badge')}</span>
        <span className={css.rewardMark} aria-hidden="true">✓</span>
        <span>{t('reasoning.reward', {
          seconds: formatSeconds(reward.watchedMs), count: formatCount(reward.grantedTokens),
        })}</span>
        <span className={css.simulated}>{rewardStatus}</span>
        <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
          {fundingLabel}
        </span>
        <QuoteSummary data={data} t={t} compact />
        <GrantLifecycle data={data} t={t} />
        {data.receipt === undefined ? null : (
          <CompactReceipt
            receipt={data.receipt}
            usage={deriveSponsorReceiptUsage(data.receipt, data.tokenConsumptions, {
              tokenGrant: data.tokenGrant,
              operatorInputSubsidyMicros: data.operatorInputSubsidyMicros,
            })}
            verification={data.adVerification}
            settlement={data.tokenGrantSettlement}
            revocation={data.tokenGrantRevocation}
            t={t}
          />
        )}
      </aside>
    )
  }

  if (playing && localAdKind === 'video') {
    const totalMs = data.playback?.durationMs ?? data.adDurationMs
    const remainingMs = Math.max(0, totalMs - elapsedMs)
    return (
      <aside className={css.videoCard} aria-label={t('reasoning.aria')} data-reasoning-sponsor="playing">
        <div className={css.videoStage}>
          <video
            key={attempt}
            ref={videoRef}
            className={css.video}
            aria-label={t('reasoning.video.aria')}
            autoPlay
            muted
            playsInline
            preload="metadata"
            disablePictureInPicture
            onEnded={() => { void completeVideo() }}
            onError={() => {
              reportAdFailure('playback-incomplete')
              setPlaying(false)
              setError('playback')
            }}
            onTimeUpdate={(event) => {
              setElapsedMs(Math.min(totalMs, Math.round(event.currentTarget.currentTime * 1_000)))
            }}
          >
            {LOCAL_SPONSOR_VIDEO_SOURCES.map(source => <source key={source.type} src={source.src} type={source.type} />)}
          </video>
          <div className={css.videoShade} aria-hidden="true" />
          <div className={css.videoTopline}>
            <span className={css.testBadge}>{t('reasoning.badge')}</span>
            <span>{t('reasoning.video.remaining', { time: clock(remainingMs) })}</span>
          </div>
          <div className={css.videoCopy}>
            <strong>{t('reasoning.sponsor')}</strong>
            <span>{t('reasoning.video.message')}</span>
            <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
              {fundingLabel}
            </span>
          </div>
          <div className={css.videoReward}>{t('reasoning.video.reward', { count: formatCount(quotedRewardTokens) })}</div>
          <div className={css.progressTrack} aria-hidden="true">
            <span style={{ width: `${Math.min(100, totalMs <= 0 ? 0 : (elapsedMs / totalMs) * 100)}%` }} />
          </div>
        </div>
        <QuoteSummary data={data} t={t} />
        <p className={css.disclosure}>{t('reasoning.disclosure')}</p>
      </aside>
    )
  }

  if (playing && localAdKind === 'tencent-native-template') {
    const remainingMs = Math.max(0, nativeTotalMs - elapsedMs)
    if (nativeCreative === null) {
      return (
        <aside className={css.nativeLoading} aria-label={t('reasoning.aria')} data-reasoning-sponsor="loading-native">
          <span className={css.pulse} aria-hidden="true" />
          <span>{t('reasoning.tencent.loading')}</span>
          <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
            {fundingLabel}
          </span>
        </aside>
      )
    }
    return (
      <aside
        className={css.nativeCard}
        aria-label={t('reasoning.tencent.aria')}
        data-reasoning-sponsor="playing-native"
        data-advertisement-id={nativeCreative.advertisementId}
      >
        <div className={css.nativeVisual}>
          <img src={nativeCreative.imageSrc} alt="" />
          <span className={css.nativeAdBadge}>{t('reasoning.tencent.adLabel')}</span>
        </div>
        <div className={css.nativeBody}>
          <div className={css.nativeTopline}>
            <strong>{t('reasoning.tencent.contract')}</strong>
            <span>{t('reasoning.tencent.remaining', { time: clock(remainingMs) })}</span>
          </div>
          <span className={css.nativeAdvertiser}>{nativeCreative.advertiser}</span>
          <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
            {fundingLabel}
          </span>
          <h4>{nativeCreative.title}</h4>
          <p>{nativeCreative.description}</p>
          <QuoteSummary data={data} t={t} />
          <GrantLifecycle data={data} t={t} />
          <div className={css.nativeFooter}>
            <span className={css.nativeButton}>{nativeCreative.buttonText}</span>
            <span>{t('reasoning.video.reward', { count: formatCount(quotedRewardTokens) })}</span>
          </div>
        </div>
        <div className={css.progressTrack} aria-hidden="true">
          <span style={{ width: `${Math.min(100, nativeTotalMs <= 0 ? 0 : (elapsedMs / nativeTotalMs) * 100)}%` }} />
        </div>
        <p className={css.nativeDisclosure}>{t('reasoning.tencent.disclosure')}</p>
      </aside>
    )
  }

  if (locallyEnded) {
    return (
      <aside className={css.rail} aria-label={t('reasoning.aria')} data-reasoning-sponsor="confirming">
        <span className={css.testBadge}>{t('reasoning.badge')}</span>
        <span className={css.pulse} aria-hidden="true" />
        <span>{localAdKind === 'tencent-native-template'
          ? t('reasoning.tencent.confirming') : t('reasoning.confirming')}</span>
        <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
          {fundingLabel}
        </span>
        <QuoteSummary data={data} t={t} compact />
        <GrantLifecycle data={data} t={t} />
      </aside>
    )
  }

  if (error !== null) {
    return (
      <aside className={`${css.rail} ${css.errorRail}`} aria-label={t('reasoning.aria')}>
        <span className={css.testBadge}>{t('reasoning.badge')}</span>
        <span role="alert">{t(`reasoning.error.${error}`)}</span>
        <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
          {fundingLabel}
        </span>
        <QuoteSummary data={data} t={t} compact />
        <GrantLifecycle data={data} t={t} />
        {error !== 'accept' || assistantStatus !== 'running' ? null : (
          <button type="button" className={css.retry} disabled={pending !== null} onClick={() => { void start() }}>
            {t('reasoning.retry.accept')}
          </button>
        )}
      </aside>
    )
  }

  if (assistantStatus !== 'running' && data.decision === undefined && !locallyAccepted) {
    return (
      <aside className={css.rail} aria-label={t('reasoning.aria')} data-reasoning-sponsor="inert">
        <span className={css.testBadge}>{t('reasoning.badge')}</span>
        <span role="status">{t('reasoning.unusedSettled')}</span>
        {data.receipt === undefined ? null : (
          <CompactReceipt
            receipt={data.receipt}
            usage={deriveSponsorReceiptUsage(data.receipt, data.tokenConsumptions, {
              tokenGrant: data.tokenGrant,
              operatorInputSubsidyMicros: data.operatorInputSubsidyMicros,
            })}
            verification={data.adVerification}
            settlement={data.tokenGrantSettlement}
            revocation={data.tokenGrantRevocation}
            t={t}
          />
        )}
      </aside>
    )
  }

  if (accepted || data.decision !== undefined || data.receipt !== undefined) {
    const status = sponsorshipUsed
      ? t('reasoning.route.used')
      : data.tokenGrant !== undefined
        ? t('reasoning.grant.issued')
        : accepted
          ? t('reasoning.accepted')
          : t('reasoning.unusedSettled')
    return (
      <aside className={css.rail} aria-label={t('reasoning.aria')} data-reasoning-sponsor="accepted">
        <span className={css.testBadge}>{t('reasoning.badge')}</span>
        {pending === null ? null : <span className={css.pulse} aria-hidden="true" />}
        <span role="status">{status}</span>
        <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
          {fundingLabel}
        </span>
        <QuoteSummary data={data} t={t} compact />
        <GrantLifecycle data={data} t={t} />
        {data.receipt === undefined ? null : (
          <CompactReceipt
            receipt={data.receipt}
            usage={deriveSponsorReceiptUsage(data.receipt, data.tokenConsumptions, {
              tokenGrant: data.tokenGrant,
              operatorInputSubsidyMicros: data.operatorInputSubsidyMicros,
            })}
            verification={data.adVerification}
            settlement={data.tokenGrantSettlement}
            revocation={data.tokenGrantRevocation}
            t={t}
          />
        )}
      </aside>
    )
  }

  return (
    <aside className={css.rail} aria-label={t('reasoning.aria')} data-reasoning-sponsor="offered">
      <span className={css.testBadge}>{localAdKind === 'tencent-native-template'
        ? t('reasoning.tencent.adLabel') : t('reasoning.badge')}</span>
      <span className={css.sponsorName}>{localAdKind === 'tencent-native-template'
        ? t('reasoning.tencent.contract') : t('reasoning.sponsor')}</span>
      <span className={css.starter}>{t('reasoning.originalRoute')}</span>
      <span className={css.fundingWarning} data-sponsor-funding-mode={data.fundingMode}>
        {fundingLabel}
      </span>
      <QuoteSummary data={data} t={t} compact />
      <button type="button" className={css.cta} disabled={pending !== null} onClick={() => { void start() }}>
        {pending === 'accept'
          ? t('reasoning.accepting')
          : pending === 'start' || pending === 'load'
            ? t('reasoning.starting') : t('reasoning.cta', { count: formatCount(quotedRewardTokens) })}
      </button>
    </aside>
  )
}
